# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72a63a557f1b001566a1a73c21584434"
name = "finally-back-in-stock"
application_url = "https://rachel-necklace-necessity-tropical.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "app-bis2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://rachel-necklace-necessity-tropical.trycloudflare.com/auth/callback",
  "https://rachel-necklace-necessity-tropical.trycloudflare.com/auth/shopify/callback",
  "https://rachel-necklace-necessity-tropical.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://finally-back-in-stock-staging-91f1859b2ef3.herokuapp.com/api/compliance"
  customer_data_request_url = "https://finally-back-in-stock-staging-91f1859b2ef3.herokuapp.com/api/compliance"
  shop_deletion_url = "https://finally-back-in-stock-staging-91f1859b2ef3.herokuapp.com/api/compliance"

[app_proxy]
url = "https://rachel-necklace-necessity-tropical.trycloudflare.com/api/hello"
subpath = "bis-api"
prefix = "apps"

[pos]
embedded = false
