# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fb4685e58265d44084c04d3cad8c365"
name = "finally-bis-test-3"
application_url = "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/auth/callback",
  "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/auth/shopify/callback",
  "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/api/compliance"
  customer_data_request_url = "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/api/compliance"
  shop_deletion_url = "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/api/compliance"

[app_proxy]
url = "https://finally-back-in-stock-test-3-d0f134a81550.herokuapp.com/api/hello"
subpath = "bis-api"
prefix = "apps"

[pos]
embedded = false
