# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac164153b025181d937b5907c40bd024"
name = "finally-bis-khair"
application_url = "https://albany-tiles-walls-stages.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-bis2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://albany-tiles-walls-stages.trycloudflare.com/auth/callback",
  "https://albany-tiles-walls-stages.trycloudflare.com/auth/shopify/callback",
  "https://albany-tiles-walls-stages.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
