# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "519033caafe14eecce8db449e3eed7b7"
name = "finally-bis-khair"
application_url = "https://reactions-optional-agents-latinas.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-bis2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://reactions-optional-agents-latinas.trycloudflare.com/auth/callback",
  "https://reactions-optional-agents-latinas.trycloudflare.com/auth/shopify/callback",
  "https://reactions-optional-agents-latinas.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
