# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4be5fc9d1ae991fced4096c5f04e5665"
name = "finally-bis-hadi"
application_url = "https://forth-confirmation-trace-equations.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-bis2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://forth-confirmation-trace-equations.trycloudflare.com/auth/callback",
  "https://forth-confirmation-trace-equations.trycloudflare.com/auth/shopify/callback",
  "https://forth-confirmation-trace-equations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
