# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8800ca44f2a3eeaa42dafeb829ea1c0b"
name = "Finally"
application_url = "https://ee-realtor-accessing-synthesis.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-bis2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://ee-realtor-accessing-synthesis.trycloudflare.com/auth/callback",
  "https://ee-realtor-accessing-synthesis.trycloudflare.com/auth/shopify/callback",
  "https://ee-realtor-accessing-synthesis.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
