spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    show-sql: true

email:
  sendgrid:
    api-url: ${EMAIL_API_URL}
    api-key: ${EMAIL_API_KEY}


app:
  url: ${SHOPIFY_APP_URL}
  aes-secret-key: ${AES_SECRET_KEY}
