-- AlterTable
ALTER TABLE "product_info" ALTER COLUMN "product_title" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "variant_title" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "product_handle" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "vendor" SET DATA TYPE VARCHAR(80);
